export const SANDBOX_CLIENT_ID = "AU4VFpRur71l6DMgUnORfFcHhA0LDboyw3MLjeAz91NLJaox2-rDOw3fcYpW1FIN8o8SAKiUL5Kk9vNi"
export const PRODUCTION_CLIENT_ID = "TO_MAKE_A_LIVE_REAL_WORLD_APPLICATION_REPLACE_THIS_TEXT_WITH_YOUR_PRODUCTION_CLIENT_ID"

export const ACCESS_LEVEL_GUEST = 0
export const ACCESS_LEVEL_USER = 1
export const ACCESS_LEVEL_ADMIN = 2


export const SERVER_HOST = `http://localhost:4000`